apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape-app
spec:
  replicas: 4  # Increase the number of replicas to 4
  selector:
    matchLabels:
      app: scrape-app
  template:
    metadata:
      labels:
        app: scrape-app
    spec:
      containers:
        - name: node-app
          image: ghcr.io/puppeteer/puppeteer:19.7.2
          workingDir: /usr/src/app
          env:
            - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
              value: "true"
            - name: PUPPETEER_EXECUTABLE_PATH
              value: /usr/bin/google-chrome-stable
          ports:
            - containerPort: 3002
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: scrape-app-service
spec:
  selector:
    app: scrape-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer  # Adjust the type based on your cluster's environment
